name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "$GOOS" = "windows" ]; then
            go build -v -o laravel-mcp-companion-go-$GOOS-$GOARCH.exe cmd/server/main.go
          else
            go build -v -o laravel-mcp-companion-go-$GOOS-$GOARCH cmd/server/main.go
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: laravel-mcp-companion-go-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}